name: Auto Labeler

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions: {}

jobs:
  auto_label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter/autolabeler@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e # v7.5.1
        with:
          config-name: release-drafter-template.yml
