name: Auto Labeler

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions: {}

jobs:
  auto_label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter/autolabeler@5de93583980a40bd78603b6dfdcda5b4df377b32 # v7.2.0
        with:
          config-name: release-drafter-template.yml
