name: Release Drafter

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: release-drafter/release-drafter@563bf132657a13ded0b01fcb723c5a58cdd824e2 # v7.2.1
        with:
          config-name: release-drafter-template.yml
